# Generated by Django 4.2.6 on 2023-10-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='Метод оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcurrecy',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='paymentcurrecy',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcurrecy', verbose_name='Валюта оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
    ]
