# Generated by Django 4.2.6 on 2023-10-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_currency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('code',), 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='payments.currency', verbose_name='Валюта'),
        ),
    ]
