# Generated by Django 4.2.6 on 2023-10-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_created_alter_payment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='requisites',
            field=models.TextField(blank=True, default=None, verbose_name='Реквизиты'),
            preserve_default=False,
        ),
    ]
