# Generated by Django 4.2.6 on 2023-10-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('payments', '0005_alter_currency_options_remove_currency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.period', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
