# Generated by Django 4.2.6 on 2023-10-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_period_active'),
        ('payments', '0006_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.period', verbose_name='Период'),
        ),
    ]
