# Generated by Django 4.2.6 on 2023-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
