# Generated by Django 4.2.6 on 2023-10-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_period_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='active',
        ),
        migrations.AddField(
            model_name='period',
            name='status',
            field=models.CharField(choices=[('todo', 'Предстоит выполнить'), ('process', 'Выполняется'), ('done', 'Выполнен')], default='todo', max_length=16, verbose_name='Статус'),
        ),
    ]
