# Generated by Django 4.2.6 on 2023-10-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('minutes', models.PositiveIntegerField(verbose_name='Кол-во минут')),
                ('report', models.FileField(upload_to='reports/work_session_report/report/', verbose_name='Отчёт')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='projects.period', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Рабочая сессия',
                'verbose_name_plural': 'Рабочие сессии',
            },
        ),
    ]
