# Generated by Django 4.2.6 on 2023-10-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksessionreport',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/work_session_report/report/', verbose_name='Отчёт'),
        ),
    ]
