# Generated by Django 4.2.6 on 2023-10-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('full_name', models.CharField(max_length=128, verbose_name='ИФО')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Никнейм')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактная информация')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplaces.marketplace', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
    ]
