# Generated by Django 4.2.6 on 2023-10-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default=None, max_length=64, unique=True, verbose_name='Никнейм'),
            preserve_default=False,
        ),
    ]
