# Generated by Django 4.2.6 on 2023-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_created_customer_updated_project_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
