# Generated by Django 4.2.6 on 2023-10-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_created_alter_customer_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
