# Generated by Django 4.2.6 on 2023-10-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_alter_marketplace_comission_and_more'),
        ('customers', '0007_project_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplaces.marketplace', verbose_name='Канал'),
        ),
    ]
