# Generated by Django 4.2.6 on 2023-10-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repository',
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('link', models.URLField(verbose_name='Ссылка на репозиторий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Репозиторий',
                'verbose_name_plural': 'Репозитории',
            },
        ),
    ]
