# Generated by Django 4.2.6 on 2023-10-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Документ')),
                ('description', models.TextField(blank=True, verbose_name='Описание документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
