# Generated by Django 4.2.6 on 2023-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_created_document_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/document/file/%Y/%m/%d/', verbose_name='Документ'),
        ),
    ]
