# Generated by Django 4.2.6 on 2023-10-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_period_active_period_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActive',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы (активные)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.order',),
        ),
        migrations.CreateModel(
            name='PeriodProcess',
            fields=[
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды (в процессе)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.period',),
        ),
        migrations.CreateModel(
            name='PeriodTodo',
            fields=[
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды (будущие)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.period',),
        ),
    ]
