# Generated by Django 4.2.6 on 2023-10-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_worksessionreport_report'),
        ('projects', '0003_remove_period_active_period_status'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodProcess',
        ),
        migrations.DeleteModel(
            name='PeriodTodo',
        ),
        migrations.CreateModel(
            name='MyPeriodProcess',
            fields=[
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды (в процессе)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.period',),
        ),
        migrations.CreateModel(
            name='MyPeriodTodo',
            fields=[
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды (будущие)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.period',),
        ),
        migrations.CreateModel(
            name='MyWorkSessionReport',
            fields=[
            ],
            options={
                'verbose_name': 'Моя рабочая сессия',
                'verbose_name_plural': 'Мои рабочие сесии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.worksessionreport',),
        ),
    ]
