# Generated by Django 4.2.6 on 2023-10-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_periodprocess_delete_periodtodo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myperiodprocess',
            options={'verbose_name': 'Мой период', 'verbose_name_plural': 'Мои периоды (в процессе)'},
        ),
        migrations.AlterModelOptions(
            name='myperiodtodo',
            options={'verbose_name': 'Мой период', 'verbose_name_plural': 'Мои периоды (будущие)'},
        ),
    ]
