# Generated by Django 4.2.6 on 2023-10-29 05:30

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('specification', models.FileField(blank=True, upload_to='services/policy/specification/%Y/%m/%d/', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Политика',
                'verbose_name_plural': 'Политики',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('specification', models.FileField(blank=True, upload_to='services/service/specification/%Y/%m/%d/', verbose_name='Спецификация')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.service', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория Услуг',
                'verbose_name_plural': 'Категории Услуг',
            },
        ),
    ]
