# Generated by Django 4.2.6 on 2023-10-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('comission', models.PositiveIntegerField(help_text='Выражается в процентах', verbose_name='Комиссионный сбор (%)')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
            },
        ),
        migrations.CreateModel(
            name='MarketPlaceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('username', models.CharField(help_text='Почта, номер телефона, имя пользователя - короче говоря логин', max_length=128, verbose_name='Никнейм')),
                ('note', models.TextField(blank=True, help_text='Не рекомендуется оставлять сюда пароли и другую конфиденциальную информацию', null=True, verbose_name='Заметка')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Учётная запись',
                'verbose_name_plural': 'Учётные записи',
            },
        ),
    ]
