# Generated by Django 4.2.6 on 2023-10-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='comission',
            field=models.PositiveIntegerField(help_text='Выражается в процентах', verbose_name='Комиссионный сбор (%)'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='note',
            field=models.TextField(blank=True, help_text='Не рекомендуется оставлять сюда пароли и другую конфиденциальную информацию', null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='username',
            field=models.CharField(help_text='Почта, номер телефона, имя пользователя - короче говоря логин', max_length=128, verbose_name='Никнейм'),
        ),
    ]
