# Generated by Django 4.2.6 on 2023-10-24 18:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_project_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_comission', models.PositiveIntegerField(verbose_name='Комиссия брокера')),
                ('budget', models.PositiveIntegerField(verbose_name='Бюджет')),
                ('starting_from', models.DateField(verbose_name='Дата начала')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('production', models.DateField(verbose_name='Продакшн')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=django.contrib.auth.models.User)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('specification', models.FileField(upload_to='orders/policy/specification/%Y/%m/%d/', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Политика',
                'verbose_name_plural': 'Политики',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('specification', models.FileField(upload_to='orders/service/specification/%Y/%m/%d/', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(verbose_name='Кол-во часов')),
                ('hour_rate', models.PositiveIntegerField(verbose_name='Ставка в час')),
                ('technical_task', models.FileField(upload_to='orders/period/technical_task/%Y/%m/%d/', verbose_name='Техническое задание')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Периоды',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='policies',
            field=models.ManyToManyField(to='orders.policy', verbose_name='Политики'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='orders.service', verbose_name='Услуги'),
        ),
    ]
