# Generated by Django 4.2.6 on 2023-10-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Период', 'verbose_name_plural': 'Периоды'},
        ),
        migrations.AlterField(
            model_name='order',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Посредник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='broker_comission',
            field=models.PositiveIntegerField(default=20, verbose_name='Комиссия посредника (%)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.PositiveIntegerField(blank=True, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='production',
            field=models.DateField(blank=True, verbose_name='Продакшн'),
        ),
        migrations.AlterField(
            model_name='period',
            name='hour_rate',
            field=models.PositiveIntegerField(verbose_name='Ставка в час ($)'),
        ),
        migrations.AlterField(
            model_name='period',
            name='technical_task',
            field=models.FileField(blank=True, upload_to='orders/period/technical_task/%Y/%m/%d/', verbose_name='Техническое задание'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='specification',
            field=models.FileField(blank=True, upload_to='orders/policy/specification/%Y/%m/%d/', verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='service',
            name='specification',
            field=models.FileField(blank=True, upload_to='orders/service/specification/%Y/%m/%d/', verbose_name='Спецификация'),
        ),
    ]
