# Generated by Django 4.2.6 on 2023-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_period_options_alter_order_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
