# Generated by Django 4.2.6 on 2023-10-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='hours',
            field=models.FloatField(verbose_name='Кол-во часов'),
        ),
    ]
