# Generated by Django 4.2.6 on 2023-10-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_deadline_alter_order_production_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AddField(
            model_name='period',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='period',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.DeleteModel(
            name='TechnicalTask',
        ),
    ]
