# Generated by Django 4.2.6 on 2023-10-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_services_period_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='None', max_length=64, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='policies',
            field=models.ManyToManyField(help_text='Политика проекта помогает понять на каких условиях готов работать заказчик и какие условия взамен готова предложить организация.<br/>', to='orders.policy', verbose_name='Политики'),
        ),
        migrations.AlterField(
            model_name='period',
            name='hours',
            field=models.PositiveIntegerField(verbose_name='Кол-во часов'),
        ),
    ]
