# Generated by Django 4.2.6 on 2023-10-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderactive_remove_order_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderactive',
            options={'verbose_name': 'Активные заказы', 'verbose_name_plural': 'Активные заказы'},
        ),
    ]
