# Generated by Django 4.2.6 on 2023-10-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderactive_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderactive',
            options={'verbose_name': 'Активный заказ', 'verbose_name_plural': 'Активные заказы'},
        ),
    ]
